name: clubs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fl_chart: ^0.69.0   


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # "uses-material-design" is indented by two spaces.
  uses-material-design: true

  # "assets:" is also indented by two spaces.
  assets:
    # The list items are indented by four spaces.
    - assets/data/snuc_clubs_massive_mock_dataset.json
    - assets/data/whatsapp/